### ISSUE TITLE
Prefer `_ is _ _` pattern

### ISSUE THREAD

**Issue by SupinePandora43** [domn1995/dunet#172]
I don't see the need in `Match` function, when the `is` pattern can work just as good (and even better, in terms of performance).
```cs
[Union]
partial record Result
{
    partial record Ok();
    partial record Error(string Id);
}
```
```cs
Result result = GetResult();

if(result is not Result.Error error)
    Console.WriteLine("Success");
else
    Console.WriteLine($"Error happened: {error.Id}");
```
```cs
Result result = GetResult();

Console.WriteLine(result switch {
    Result.Ok => "Success",
    Result.Error error => $"Error happened: {error.Id}",
    _ => $"Unknown: {result}"
});
```

**Comment by domn1995** [comment]
The `Match` method provides exhaustive pattern matching at compile time. Consider that you add another variant to your `Result` union above. Your final code block would still compile because you are discarding all other values. If you use the `Match` method instead, the compiler will raise an error  saying that you aren't handling the new variant that was added. If you do not need exhaustive matching, feel free to use the `is` pattern or switch expression with a discard like in your second code block.
